#mqtt_hostname: test-broker.crystalpower.in
mqtt_hostname: Broker.recpdcl.com
mqtt_port: 8883
mqtt_username: mosquittouser
mqtt_password: eKEVUy4onvzOHrzPHTmRCcgca9j2AOD
#mqtt_force_unsecure: true
gateway_id: JASU102098
